[book]
title = "GPUI"
description = "A book teaching you the concepts you need to create your own GPUI application."
authors = ["Matin Aniss"]
language = "en"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/MatinAniss/gpui-book"
site-url = "/gpui-book/"

[output.html.playground]
runnable = false
